/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelDominio.Categoria;
import modelDominio.Veiculo;
import view.util.ComboBoxUsuario;
import view.util.Imagem;

/**
 *
 * @author profe
 */
public class VeiculoForm extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VeiculoForm.class.getName());
    private Veiculo veiculo;
    private Imagem imagem = null;



    public VeiculoForm() {
        initComponents();
         preencheComboboxMarcas(-1);
   }
    private void preencheComboboxMarcas(int codigo) {
        // preenchendo o comboBox dos Marcas
        ArrayList<Categoria> lista = new ArrayList<Categoria>();
        lista = RevendaCliente.conexaocontroller.categoriaLista();
        ComboBoxUsuario.preencheComboBoxUsuario(codigo, 
                jComboBoxCategoria, lista,false);
    }
    public void setCategoria(Veiculo v) {
        inputPlaca.setText(v.getPlaca());
        inputCor.setText(v.getCor());
        inputModelo.setText(v.getModelo());
        //inputCategoria.setText(String.valueOf(v.getCategoria()));
                preencheComboboxMarcas(v.getCategoria().getId());

                    imagem = new Imagem(v.getImagem());

                    jLabelImagem.setIcon(imagem.getImageIcon());

        this.veiculo = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputPlaca = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputCor = new javax.swing.JTextField();
        inputModelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnImagem = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jComboBoxCategoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Placa");

        inputPlaca.addActionListener(this::inputPlacaActionPerformed);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        jLabel2.setText("Cor");

        jLabel3.setText("Modelo");

        jLabel4.setText("Categoria");

        btnImagem.setText("Carregar imagem");
        btnImagem.addActionListener(this::btnImagemActionPerformed);

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(30, 30, 30)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnEnviar)
                    .addComponent(btnImagem))
                .addGap(647, 647, 647)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(inputCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(inputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImagem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(btnEnviar)
                .addGap(367, 367, 367))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        boolean result = false;
        int codCategoria = ComboBoxUsuario.getSelectedIndex(jComboBoxCategoria);        

        if (veiculo != null) {
            // editando
            Veiculo veiculoEditar;
            veiculoEditar = 
                    new Veiculo(veiculo.getPlaca(), inputModelo.getText(), inputCor.getText(), new Categoria(codCategoria), imagem.getImagem());

            result = 
                    RevendaCliente.conexaocontroller.
                            veiculoEditar(veiculoEditar);
        } else {
            if (inputPlaca.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Preencha o Nome!");
                inputPlaca.requestFocus();
            } else {
                Veiculo veiculoInserir = 
                        new Veiculo(inputPlaca.getText(), inputModelo.getText(), inputCor.getText(), new Categoria(codCategoria), imagem.getImagem());


                result = RevendaCliente.conexaocontroller.veiculoInserir(veiculoInserir);
            }
            
        }
        if (result) {
                JOptionPane.showMessageDialog(this, "Veiculo adicionado!");
                dispose();
                
            } else {
                JOptionPane.showMessageDialog(this, "Erro adicionando/editando Veiculo!");
            }

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void inputPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPlacaActionPerformed

    private void btnImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagemActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter imageFilter = 
                new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        JFileChooser jFileChooser2 = new JFileChooser();
        jFileChooser2.addChoosableFileFilter(imageFilter);
        if (jFileChooser2.showOpenDialog(this) ==  JFileChooser.APPROVE_OPTION){
            imagem = new Imagem(jFileChooser2.getSelectedFile());
            jLabelImagem.setIcon(imagem.getImageIcon());
        }
    }//GEN-LAST:event_btnImagemActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnImagem;
    private javax.swing.JTextField inputCor;
    private javax.swing.JTextField inputModelo;
    private javax.swing.JTextField inputPlaca;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImagem;
    // End of variables declaration//GEN-END:variables
}
